### ISSUE TITLE
💬 Kotools are Kool Types for Kotlin Multiplatform

### ISSUE THREAD

**Issue by jmfayard** [kotools/types#338]
A new improved tagline suggestion :)

**Comment by LVMVRQUXL** [comment]
I like it @jmfayard! We may display this tagline in the README below badges as a testimony if you are okay?

**Comment by jmfayard** [comment]
oeuf corse

Le jeu. 1 févr. 2024 à 16:13, Loïc Lamarque ***@***.***> a
écrit :

**Comment by LVMVRQUXL** [comment]
@jmfayard I'm gonna add it as a tagline like suggested shortly. Stay tuned. 😉

**Comment by LVMVRQUXL** [comment]
@jmfayard Your tagline is available in the [README](https://github.com/kotools/types/blob/main/README.md) documentation. 🎉
Thank you for your suggestion! 🙏
