### ISSUE TITLE
`types-internal` subproject missing in Kotools Types 4.4.0

### ISSUE THREAD

**Issue by robertfmurdock** [kotools/types#406]
## Description

> Bug encountered in version `4.4.0`.

Latest version does not resolve correctly in Gradle dependency tree. Appears to depend on a "types/internal/4.4.0" library that is not available in Maven Central.

## Checklist

- [ ] Fix.
- [ ] Update the `Unreleased` section in the changelog.

**Comment by LVMVRQUXL** [comment]
Thank you for reporting this bug @robertfmurdock.
We managed to reproduce it locally and will to a fix really soon.

**Comment by LVMVRQUXL** [comment]
This bug was fixed locally @robertfmurdock.
We are now preparing a patch release for publishing this fix as soon as possible.

**Comment by LVMVRQUXL** [comment]
@robertfmurdock The fix for this issue is available in [Kotools Types 4.4.1](https://github.com/kotools/types/releases/tag/4.4.1).
