### ISSUE TITLE
`unaryMinus` operation for `AnyInt` hierarchy

### ISSUE THREAD

**Issue by LVMVRQUXL** [kotools/types#54]
## Description

> Discussed in https://github.com/kotools/types/discussions/40.

We would like to introduce the following `unaryMinus` **experimental** operations for the `AnyInt` hierarchy:

```kotlin
/** Returns the negative of this integer. */
operator fun AnyInt.unaryMinus(): Int
operator fun NonZeroInt.unaryMinus(): NonZeroInt
operator fun PositiveInt.unaryMinus(): NegativeInt
operator fun NegativeInt.unaryMinus(): PositiveInt
operator fun StrictlyPositiveInt.unaryMinus(): StrictlyNegativeInt
operator fun StrictlyNegativeInt.unaryMinus(): StrictlyPositiveInt
```

## Checklist

> Tests should be done at least on the JVM platform!

- [x] Wait for the issue #66 to be resolved for using the `ExperimentalNumberApi` annotation.
- [x] Wait for the issue #82 to be resolved for working on safer commits.
- [x] Implement and test it for the `AnyInt` type.
- [x] Implement and test it for the `NonZeroInt` type.
- [x] Implement and test it for the `PositiveInt` type.
- [x] Implement and test it for the `NegativeInt` type.
- [x] Implement and test it for the `StrictlyPositiveInt` type.
- [x] Implement and test it for the `StrictlyNegativeInt` type.
- [x] Refactor code.
- [x] Check and update the public API binaries.
- [x] Update the `Unreleased` section in the changelog.

**Comment by MichaelStH** [comment]
Can I take this one ?

**Comment by LVMVRQUXL** [comment]
> Can I take this one ?

Sure, I will assigne it to you.

**Comment by LVMVRQUXL** [comment]
> Can I take this one ?

Sure, I will assign it to you!

**Comment by LVMVRQUXL** [comment]
Because this issue will be included in Kotools Types 4.2.0, make sure to add the `@SinceKotoolsTypes("4.2")` annotation on new declarations introduced by this issue.
Also, if you use IntellIJ, I suggest you to run:
- the `Documentation` configuration for generating the documentation with auto-reload.
- the `JVM test` configuration for testing your code.

**Comment by LVMVRQUXL** [comment]
@MichaelStH Please remember to pull changes from the `main` branch and base your branch on it before implementing it: I've added an [`.editorconfig` file](https://github.com/kotools/types/commit/0adf59318a6a97c34a2bf0343dfbe11ceac332ce) for normalizing the style code of this project.

**Comment by LVMVRQUXL** [comment]
@MichaelStH Please remember to pull changes from the `main` branch and base your branch on its latest commit before implementing it: I've cleaned the Git history until the tag [`4.2.0-alpha`](https://github.com/kotools/types/releases/tag/4.2.0-alpha).
Sorry for the inconvenience.

**Comment by LVMVRQUXL** [comment]
@MichaelStH Quick update! 🚨
I'm currently verifying each commits for enhancing the security of the project, and because it involves updating the Git history, I'm gonna mark this issue as blocked by the issue #82.

If you've already published some work on the corresponding branch (`feature/54` for example), please push your changes to the repository. I will rebase it once this security work is done.
If not, then do nothing. I will put a new update on this issue when the issue #82 will be completed.

Sorry again for the inconvenience.

**Comment by LVMVRQUXL** [comment]
@MichaelStH The issue #82 is done! You can now work on this issue.
