### ISSUE TITLE
🚚 Renaming argument of factory functions for `EmailAddress`

### ISSUE THREAD

**Issue by LVMVRQUXL** [kotools/types#616]
## 📝 Description

For better consistency of our API, we want to rename the `text` argument of the factory functions for the `EmailAddress` type as `value`.

Here's an example of calling the `EmailAddress.Companion.create(String)` function from Kotlin code using named parameters:

```kotlin
EmailAddress.create(text = "contact@kotools.org") // Actual
EmailAddress.create(value = "contact@kotools.org") // Expected
```

> [!IMPORTANT]
> This is an **incompatible source** change. See our [versioning strategy](https://github.com/kotools/types/blob/main/documentation/versioning-strategy.md) for more details on when we can publish it.

## ✅ Checklist

- [ ] Rename the argument of the `EmailAddress.Companion.create(String)` function.
- [ ] Improve the Kotlin tests of the `EmailAddress.Companion.create(String)` function by calling it with named arguments.
- [ ] Rename the argument of the `EmailAddress.Companion.createOrNull(String)` function.
- [ ] Improve the Kotlin tests of the `EmailAddress.Companion.create(String)` function by calling it with named arguments.
- [ ] Add an entry for this change in the [unreleased changelog](https://github.com/kotools/types/blob/main/CHANGELOG.md).

**Comment by augustomtt** [comment]
hey! I want to tackle this issue, I'm going to create a PR soon!

**Comment by LVMVRQUXL** [comment]
Hello @augustomtt! 👋

Thank you for considering to work on this issue. 🙏

These functions will be deprecated by #623 in favor of using a public constructor instead. This design choice will improve the readability and the predictability of client's code when creating an email address. I've created the issue yesterday but I forgot to update this one. Sorry for the inconvenience. 😅

We have more [good first issues](https://github.com/kotools/types/labels/good%20first%20issue) that you might be interested in contributing, so feel free to tackle them. I will be happy to review your pull requests! 😁

P.S.: You might be interested in tackling #618 or #624 for the next release. 👀
